.TH "bm-applet" "1" 
.SH "NAME" 
bm-applet \(em Barcode scanner management framework 
.SH "SYNOPSIS" 
.PP 
\fBbm-applet\fR 
.SH "DESCRIPTION" 
.PP 
\fBbm-applet\fR is the GNOME front-end for BarcodeManager 
.PP 
It is a systray applet which will display an icon in GNOME's notification area but it  
also works for other desktop environments which provide a systray like KDE or XFCE. 
.PP 
\fBbm-applet\fR shows a list of available barcode scanners and allows you to easily switch between them.
.SH "SEE ALSO" 
.PP 
BarcodeManager (1)
.PP 
More Information about BarcodeManager can be found at 
http://github.com/koppi/barcode-utils . 
.SH "AUTHOR" 
.PP 
This manual page was written by Jakob Flierl jakob.flierl@gmail.com for 
the \fBDebian\fP system. 
 
.\" created by instant / docbook-to-man, Sun 27 Nov 2011, 02:40 
