#!/bin/sh
#
# output to Test-1.0.vapi because for now we need to maintain
# Barman-1.0.vapi manually :(

set -x

g-ir-scanner \
    --add-include-path=. \
    --namespace=Barman \
    --nsversion=1.0 \
    --libtool="/bin/bash ../../libtool"  \
    --include=GObject-2.0 \
    --include=Gio-2.0  \
    --library=libbarman.la \
    --output Barman-1.0.gir \
    --warn-all \
    barman.h barman-manager.c barman-manager.h \
    barman-service.c barman-service.h \
    barman-ipv4.c barman-ipv4.h \
    barman-ipv6.c barman-ipv6.h \
    libbarman.la

vapigen \
    --library=Barman-1.0 \
    --pkg glib-2.0 \
    --pkg gio-2.0 \
    --vapidir=. \
    Barman-1.0.gir
