#!/bin/sh

usage() {
    echo "Usage: indicator-barcode-debug start|stop"
    exit 1
}

service_debug() {
    case $1 in
	enable)
	    level=1
	    ;;
	disable)
	    level=0
	    ;;
	*)
	    echo "Invalid parameter for service"
	    exit 2
	    ;;
    esac

    dbus-send --session --dest=com.canonical.indicator.network \
	/com/canonical/indicator/network/service \
	com.canonical.indicator.network.SetDebug int32:$level
}

agent_debug() {
    case $1 in
	enable)
	    level=1
	    ;;
	disable)
	    level=0
	    ;;
	*)
	    echo "Invalid parameter for agent"
	    exit 2
	    ;;
    esac

    dbus-send --session --dest=com.canonical.indicator.network.agent \
	/com/canonical/indicator/network/agent \
	com.canonical.indicator.network.agent.SetDebug int32:$level
}

start() {
    sudo indicator-barcode-daemon-debug start

    service_debug enable
    agent_debug enable

    echo "All network components are now running in debug mode."
}

stop() {
    sudo indicator-barcode-daemon-debug stop

    service_debug disable
    agent_debug disable

    echo "All network components are now running in normal mode."
}

if [ "$#" != 1 ]; then
    usage
fi

case $1 in
    start)
	start
	;;
    stop)
	stop
	;;
    *)
	echo "Invalid commmand"
	usage
	exit 2
	;;
esac
