#!/usr/bin/python
#
# barman-mock - barman dbus mock
#
# Copyright 2010 Canonical Ltd.
#
# Authors:
# Kalle Valo <kalle.valo@canonical.com>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import dbus
import sys

def usage():
      print "Usage: %s <type> [count]" % (sys.argv[0])
      sys.exit(1)

def main():
      if (len(sys.argv) < 2 or len(sys.argv) > 3):
            usage()

      service_type = sys.argv[1]

      if len(sys.argv) == 3:
            count = int(sys.argv[2])
      else:
            count = 1

      bus = dbus.SystemBus()
      manager = dbus.Interface(bus.get_object("net.barman", "/"),
                               "com.canonical.barman.mock.Manager")

      while count > 0:
            path = manager.CreateService(service_type)
            print path
            count = count - 1

if __name__ == "__main__":
    main()
      

