#!/usr/bin/python
#
# barman-mock - barman dbus mock
#
# Copyright 2010 Canonical Ltd.
#
# Authors:
# Kalle Valo <kalle.valo@canonical.com>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import dbus
import sys

def usage():
      print "Usage: %s <path>" % (sys.argv[0])
      sys.exit(1)

def main():
      if len(sys.argv) != 2:
            usage()

      path = sys.argv[1]

      bus = dbus.SystemBus()
      manager = dbus.Interface(bus.get_object("net.barman", "/"),
                               "com.canonical.barman.mock.Manager")
      manager.RemoveService(path)

if __name__ == "__main__":
    main()
      

